name: Auto-merge codex -> main

on:
  push:
    branches: [ "codex" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ensure-pr-and-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create or update PR
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(codex): sync"
          title: "codex → main (auto)"
          body: "Automated PR from codex branch."
          branch: "codex"
          base: "main"
          labels: "codex, automated"
          draft: false

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

      - name: Note
        if: steps.cpr.outputs.pull-request-number != ''
        run: echo "Auto-merge произойдёт при прохождении required checks (включите branch protection для main)."
