name: auto-merge-codex

on:
  push:
    branches: [codex]
  pull_request:
    branches: [main]

jobs:
  pr_automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Guard: tasks file must exist
        run: |
          if [ ! -f docs/CODEX_TASKS.md ]; then
            echo "::error file=docs/CODEX_TASKS.md::Missing tasks file"
            exit 1
          fi

      - name: OK
        run: echo "guard passed"

