name: Auto-merge codex → main (light)

on:
  push:
    branches: [ codex ]
  workflow_dispatch:

concurrency:
  group: automerge-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create/Update PR & enable auto-merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          PR_NUM=$(gh pr list --base main --head codex --json number --jq '.[0].number' || true)
          if [ -z "${PR_NUM:-}" ] || [ "${PR_NUM}" = "null" ]; then
            gh pr create --base main --head codex \
              --title "Auto: codex → main" \
              --body  "Automated PR created on push to 'codex'."
            PR_NUM=$(gh pr list --base main --head codex --json number --jq '.[0].number')
          fi
          gh pr edit  "$PR_NUM" --add-label "auto"
          gh pr merge "$PR_NUM" --auto --squash
