mkdir -p /home/nod/codex_projects/1/.github/workflows
cat > /home/nod/codex_projects/1/.github/workflows/auto-merge-codex.yml <<'YML'
name: Auto-merge codex → main (light)

on:
  push:
    branches: [ codex ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or update PR codex → main
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "auto(codex): iteration"
          title: "auto(codex): iteration"
          body: "Automated update from Codex loop"
          base: main
          branch: codex
          delete-branch: false
          draft: false

      - name: Enable auto-merge (squash)
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
YML

cd /home/nod/codex_projects/1
git add .github/workflows/auto-merge-codex.yml
git commit -m "ci: add single stable auto-merge workflow"
git push -u origin codex

