name: CI build & auto-merge codex → main

on:
  push:
    branches: [ codex ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  build_and_automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install deps (monorepo-safe)
        run: |
          (npm ci || npm install) || true
          if [ -d frontend ] && [ -f frontend/package.json ]; then (cd frontend && (npm ci || npm install) || true); fi
          if [ -d apps/svc-vendors ] && [ -f apps/svc-vendors/package.json ]; then (cd apps/svc-vendors && (npm ci || npm install) || true); fi
          if [ -d types ] && [ -f types/package.json ]; then (cd types && (npm ci || npm install) || true); fi

      - name: Lint (soft)
        run: |
          npx eslint . || echo "eslint warnings/errors ignored for gate"

      - name: Build (soft; фронт и корень, если есть)
        run: |
          if [ -f package.json ]; then (npm run build || echo "root build soft"); fi
          if [ -d frontend ] && [ -f frontend/package.json ]; then (cd frontend && (npm run build || echo "frontend build soft")); fi

      - name: Create/Update PR and enable auto-merge (squash)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          PR_NUM=$(gh pr list --base main --head codex --json number --jq '.[0].number' || true)
          if [ -z "${PR_NUM:-}" ] || [ "${PR_NUM}" = "null" ]; then
            gh pr create --base main --head codex \
              --title "Auto: codex → main (CI)" \
              --body  "CI completed. Auto-merge enabled."
            PR_NUM=$(gh pr list --base main --head codex --json number --jq '.[0].number')
            echo "Created PR #$PR_NUM"
          else
            echo "PR exists: #$PR_NUM"
          fi
          gh pr edit  "$PR_NUM" --add-label "auto"
          gh pr merge "$PR_NUM" --auto --squash

      - name: Summary
        run: echo "✅ Auto-merge is enabled for PR codex → main."
