# .github/workflows/codex-pr.yml
# ВЕРСИЯ: FINAL-STABLE

name: 'Codex PR'

on:
  push:
    branches:
      - 'codex'
    # Игнорируем изменения ТОЛЬКО в документации, чтобы не создавать лишние PR
    paths-ignore:
      - 'docs/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create or Update PR'
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Используем только валидные параметры
          branch: 'codex'
          title: 'auto(codex): new updates'
          body: 'Автоматическое обновление кода от Codex-агента.'
          author: 'olegin77 <codex@automation.local>'
