# .github/workflows/codex-pr.yml

name: 'Codex PR'

on:
  push:
    branches:
      - 'codex'
    # ❗️ КЛЮЧЕВОЕ ИЗМЕНЕНИЕ:
    # Запускаем воркфлоу, ТОЛЬКО если изменения коснулись чего-либо ВНЕ папки /docs
    paths-ignore:
      - 'docs/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create or Update PR'
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          branch: 'codex'
          title: 'auto: codex update'
          body: 'Автоматическое обновление кода от Codex-агента.'
          author: 'olegin77 <codex@automation.local>'
          # Важно: разрешаем пустые коммиты, чтобы PR не закрывался
          allow_empty_commits: true
