name: codex-pr

on:
  push:
    branches: [codex]

permissions:
  contents: write
  pull-requests: write

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure GitHub CLI installed
        run: |
          if ! command -v gh >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y gh
          fi

      - name: Check diff codex vs main
        id: diff
        run: |
          git fetch origin main codex --quiet
          if git diff --quiet origin/main..origin/codex; then
            echo "has_diff=false" >> "$GITHUB_OUTPUT"
            echo "No diff between origin/main and origin/codex"
          else
            echo "has_diff=true" >> "$GITHUB_OUTPUT"
            echo "Diff detected"
          fi

      - name: Ensure PR codex -> main exists
        if: steps.diff.outputs.has_diff == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          prnum="$(gh pr list --state open --base main --head codex --json number --jq '.[0].number' || true)"
          if [[ -z "${prnum:-}" ]]; then
            echo "Creating PR codex -> main..."
            gh pr create --base main --head codex \
              --title "auto: codex update" \
              --body "Auto PR from codex."
            prnum="$(gh pr list --state open --base main --head codex --json number --jq '.[0].number')"
          else
            echo "PR #$prnum already exists."
          fi
          echo "PR_NUMBER=$prnum" >> "$GITHUB_ENV"

      - name: Enable auto-merge (squash; best-effort)
        if: env.PR_NUMBER != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge "$PR_NUMBER" --squash --auto || echo "automerge not enabled; continue"
