name: pr-guard

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  tasks_guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure docs/CODEX_TASKS.md exists and non-empty
        run: |
          if [ ! -f docs/CODEX_TASKS.md ]; then
            echo "::error file=docs/CODEX_TASKS.md::Missing tasks file"
            exit 1
          fi
          if [ ! -s docs/CODEX_TASKS.md ]; then
            echo "::error file=docs/CODEX_TASKS.md::Empty tasks file"
            exit 1
          fi

      - name: OK
        run: echo "guard passed"
